### PR TITLE
[WIP] Extract module class loader and autoloader into separate module

### PR DESCRIPTION
**Pull request by Xerkus**
Get rid of `Zend\Loader` dependency in backwards (mostly)compatible way

### CODE REVIEW

**Comment by Xerkus** [comment]
It is not that much of a break, it will require installing additional package `zendframework/zend-modulemanager-autoloader`

**Comment by Xerkus** [comment]
And yes, next major release should have it removed completely

**Comment by Xerkus** [comment]
heh. discovered bug where test was not failing because another test, removed here, loaded required class

**Comment by weierophinney** [comment]
I agree with @Ocramius here. If the code will still be in `ModuleManager` to test for the classes and register them, there is tight integration. It makes more sense to create a release in the 2.X series indicating that the features are deprecated and will be removed in the next major release, as we can then also remove the tight-coupling, and will not need to maintain an additional repository that will only be abandoned.

**Pull request closed without merging**
