### PR TITLE
Docs formatting fixes

### PR DESCRIPTION
**Pull request by Xerkus**
- [x] #20 Headers and levels
- [x] #21 Code blocks
- [ ] #22 Other things
- [x] #23 Tables
- [x] #24 Blockquotes

### CODE REVIEW

**Comment by froschdesign** [comment]
@Xerkus 
First step looks good to me! :+1:

**Comment by froschdesign** [comment]
@Xerkus 
I think, the headlines for notes should follow the header hierarchy / outline of the current document.

Example: ([Module Autoloader](https://github.com/zendframework/zend-modulemanager/blob/master/doc/book/zend.module-manager.module-autoloader.md))
```markdown
# The Module Autoloader
## Module Autoloader Usage
### Note
### Note
## Non-Standard / Explicit Module Paths
## Packaging Modules with Phar
## Note
```
Both notes related to "Module Autoloader Usage".

**Comment by Xerkus** [comment]
@francisdaigle by html spec blockquotes and their headings are not part of outline. It should not matter, at least in theory, and making them context dependent might make them look different.

I am ok with either approach so i will leave the call to someone else.

> Certain elements are said to be sectioning roots, including blockquote and td elements. These elements can have their own outlines, but the sections and headings inside these elements do not contribute to the outlines of their ancestors.

**Comment by froschdesign** [comment]
@Xerkus 
> by html spec blockquotes and their headings are not part of outline.

You are [right](http://www.w3.org/TR/html5/sections.html#headings-and-sections).

(Btw. I am not "francisdaigle". :wink:)

**Comment by Xerkus** [comment]
@froschdesign oops. used autocompletion and didn't even notice.

**Comment by GeeH** [comment]
@Xerkus @froschdesign - either is fine just submit PR and I'll make that the standard.

**Comment by Xerkus** [comment]
Links to other components are left untouched for now. They will need to be updated once docs for those components are migrated and when we know what those links are supposed to be.

**Comment by GeeH** [comment]
Thanks @Xerkus :candy:

**Pull request merged**
